from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime

def generate_grade_pdf(student_name, grades, program="BSc. Computer Science", semester="Semester 1", year="2025"):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawCentredString(width / 2, height - 50, "Student Management System")
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawCentredString(width / 2, height - 80, "Official Grade Report")
    pdf.line(50, height - 95, width - 50, height - 95)

    # Student info (with default program, semester, year)
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 120, f"Student Name: {student_name}")
    pdf.drawString(50, height - 140, f"Program: {program}")
    pdf.drawString(50, height - 160, f"Semester: {semester}")
    pdf.drawString(50, height - 180, f"Year: {year}")
    pdf.drawString(50, height - 200, f"Date: {datetime.now().strftime('%d-%m-%Y')}")

    # Table header
    y = height - 240
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "Course")
    pdf.drawString(250, y, "Score")
    pdf.drawString(350, y, "Grade")
    pdf.line(50, y - 5, width - 50, y - 5)
    y -= 25

    # Table rows
    pdf.setFont("Helvetica", 11)
    for g in grades:
        course_display = f"{g['course_id']} - {g['course_name']}"
        pdf.drawString(50, y, course_display)
        pdf.drawString(250, y, str(g['score']))
        pdf.drawString(350, y, str(g['grade']))
        y -= 20
        if y < 100:
            pdf.showPage()
            pdf.setFont("Helvetica-Bold", 14)
            pdf.drawCentredString(width / 2, height - 50, "Grade Report (continued)")
            pdf.setFont("Helvetica", 11)
            y = height - 100

    # Footer
    pdf.line(50, 80, width - 50, 80)
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.drawCentredString(width / 2, 60, "This is a system-generated report. No signature required.")
    pdf.drawCentredString(width / 2, 45, "Generated by Student Management System")

    pdf.save()
    buffer.seek(0)
    return buffer